version: "3"
services:

  jdwp_server:
    # build: .
    image: tomcat:8
    container_name: jdwp-codeexecute
    expose: 
      - "8080"
      - "5005"
    ports:
      - 8080:8080
      - 5005:5005
    restart: always
    environment:
      - CATALINA_OPTS=-server -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
      - TZ=Asia/Shanghai